export const subjectOptions = [
  { value: "Mathematics", label: "Toán" },
  { value: "Literature", label: "Ngữ văn" },
  { value: "English", label: "Tiếng Anh" },
  { value: "Physics", label: "Vật lý" },
  { value: "Chemistry", label: "Hóa học" },
  { value: "Biology", label: "Sinh học" },
  { value: "History", label: "Lịch sử" },
  { value: "Geography", label: "Địa lý" },
  { value: "CivicEducation", label: "Giáo dục công dân" },
  { value: "Informatics", label: "Tin học" },
  { value: "Technology", label: "Công nghệ" },
  { value: "PhysicalEducation", label: "Thể dục" },
  { value: "Music", label: "Âm nhạc" },
  { value: "Art", label: "Mỹ thuật" },
  { value: "DefenseEducation", label: "Giáo dục quốc phòng" },
  { value: "Science", label: "Khoa học tự nhiên" },
  { value: "SocialScience", label: "Khoa học xã hội" },
  { value: "Ethics", label: "Đạo đức" },
  { value: "CareerOrientation", label: "Hướng nghiệp" },
  { value: "Reading", label: "Đọc hiểu" },
  { value: "Writing", label: "Tập làm văn" },
  { value: "MathematicalLogic", label: "Toán tư duy" },
  { value: "ComputerScience", label: "Khoa học máy tính" },
  { value: "Programming", label: "Lập trình" },
  { value: "STEM", label: "STEM" },
  { value: "LifeSkills", label: "Kỹ năng sống" },
  { value: "EnvironmentalEducation", label: "Giáo dục môi trường" },
  { value: "MoralEducation", label: "Giáo dục đạo đức" },
  { value: "Astronomy", label: "Thiên văn học" },
  { value: "Economics", label: "Kinh tế học" },
  { value: "Psychology", label: "Tâm lý học" },
  { value: "Philosophy", label: "Triết học" },
];


export const gradeOptions = [
  {value: 1, label: "Lớp 1"},
  {value: 2, label: "Lớp 2"},
  {value: 3, label: "Lớp 3"},
  {value: 4, label: "Lớp 4"},
  {value: 5, label: "Lớp 5"},
  {value: 6, label: "Lớp 6"},
  {value: 7, label: "Lớp 7"},
  {value: 8, label: "Lớp 8"},
  {value: 9, label: "Lớp 9"},
  {value: 10, label: "Lớp 10"},
  {value: 11, label: "Lớp 11"},
  {value: 12, label: "Lớp 12"},
]
